import { AspectRatio, Box, Container, Divider, Heading, IconButton, Image } from '@chakra-ui/react';
import { GetServerSideProps, InferGetServerSidePropsType } from 'next';
import Head from 'next/head';
import router from 'next/dist/client/router';

import { cookieHandler, fetchBuilder } from 'utils/utils';
import { ArrowBackIcon } from '@chakra-ui/icons';

export const getServerSideProps: GetServerSideProps = async (context) => {
  const eventId = context.params?.event_id;
  const cookies = context.req.headers.cookie;
  try {
    const res = await fetchBuilder(`events/${eventId}`, cookieHandler(cookies, 'user_session'));
    const event = await res.data;
    return {
      props: { event },
    };
  } catch (err) {
    throw err;
  }
};

const Event = ({ event }: InferGetServerSidePropsType<typeof getServerSideProps>) => {
  return (
    <div>
      <Head>
        <title>{event.title}</title>
        <meta content='Generated by create next app' name='description' />
        <link href='/favicon.ico' rel='icon' />
      </Head>
      <Container maxW='container.lg' mt='25px'>
      <IconButton variant='outline' isRound colorScheme='teal' aria-label='Add event' onClick={() => router.push("/")} icon={<ArrowBackIcon />} />
        <Box borderWidth='1px' borderRadius='lg' mt={5} overflow='hidden' >
          <AspectRatio width={'fill-content'} ratio={32 / 9}>
            <Image src={event.picture} alt={event.title} />
          </AspectRatio>
          <Box p='6'>
            <Box mt='1' fontWeight='semibold' as='h4' lineHeight='tight' isTruncated>
              <Heading>{event.title}</Heading>
            </Box>
            <Box d='flex' alignItems='baseline'>
              <Box color='gray.500' fontWeight='semibold' letterSpacing='wide' fontSize='sm' mt={3} textTransform='uppercase'>
                {`${event.location} - ${event.start_date_time}`}
              </Box>
            </Box>
            <Divider />
            <Box d='flex' alignItems='baseline'>
              <Box fontWeight='semibold' letterSpacing='wide' fontSize='sm' mt={3}>
                {event.description}
              </Box>
            </Box>
          </Box>
        </Box>
      </Container>
    </div>
  );
};

export default Event;
