import { gql, useMutation } from '@apollo/client';
import { ArrowBackIcon } from '@chakra-ui/icons';
import { Button, Container, Heading, IconButton, useToast } from '@chakra-ui/react';
import Input from 'components/form/Input';
import router from 'next/dist/client/router';
import Head from 'next/head';
import { useRef } from 'react';
import { useForm } from 'react-hook-form';

const CREATE_EVENT = gql`
  mutation CreateEventQuery($event: CreateEventDtoInput!) {
    createEvent(event: $event) {
      id
    }
  }
`;

const Event = () => {
  const toast = useToast({ duration: 3000, position: 'bottom-left' });
  const toastIdRef = useRef();
  const {
    handleSubmit,
    register,
    formState: { errors, isSubmitting },
  } = useForm();
  const [createEvent] = useMutation(CREATE_EVENT, {
    onCompleted: (data) => {
      console.log(data);
      toast({
        title: 'Event created',
        status: 'success',
      });
      router.push(`/event/${data.createEvent.id}`);
    },
    onError: (err) => {
      toast({
        title: err.message,
        status: 'error',
      });
    },
  });

  const onSubmit = (values: any) => {
    createEvent({ variables: { event: values } });
  };

  return (
    <div>
      <Head>
        <title>Creating event</title>
        <meta content='Generated by create next app' name='description' />
        <link href='/favicon.ico' rel='icon' />
      </Head>
      <Container maxW='container.lg' mt='25px'>
        <Heading m='25px 0' size='2xl'>
          <IconButton aria-label='Add event' colorScheme='teal' icon={<ArrowBackIcon />} isRound onClick={() => router.push('/')} variant='outline' /> Create
          Event
        </Heading>
        <form onSubmit={handleSubmit(onSubmit)}>
          <Input errors={errors} name='title' placeholder='Coachella Party' register={register} title='Event title' />
          <Input errors={errors} name='location.contextualName' placeholder='Place' register={register} title='Place' />
          <Input errors={errors} name='picture' placeholder='https://coolimage.png' register={register} title='Picture' />
          <Input errors={errors} multiline name='description' placeholder='This party is gonna be lit...' register={register} title='Description' />
          <Input errors={errors} name='startDate' placeholder='2022-03-13T12:00:00+01:00' register={register} title='Start' />
          <Input errors={errors} name='endDate' placeholder='2022-03-14T12:00:00+01:00' register={register} title='End' />
          <Button colorScheme='teal' isLoading={isSubmitting} mt={4} type='submit'>
            Submit
          </Button>
        </form>
      </Container>
    </div>
  );
};

export default Event;
