import { Button, Container, Heading, IconButton } from '@chakra-ui/react';
import axios from 'axios';
import Input from 'components/form/Input';
import Head from 'next/head';
import { useForm } from 'react-hook-form';
import router from 'next/dist/client/router';
import { ArrowBackIcon } from '@chakra-ui/icons';

const Event = () => {
  const {
    handleSubmit,
    register,
    formState: { errors, isSubmitting },
  } = useForm();

  function onSubmit(values: any) {
    axios.post(`events`, values)
  }

  return (
    <div>
      <Head>
        <title>Creating event</title>
        <meta content='Generated by create next app' name='description' />
        <link href='/favicon.ico' rel='icon' />
      </Head>
      <Container maxW='container.lg' mt='25px'>
      <Heading size='2xl' m='25px 0'>
        <IconButton variant='outline' isRound colorScheme='teal' aria-label='Add event' onClick={() => router.push("/")} icon={<ArrowBackIcon />} />
          {" "} Create Event
        </Heading>
        <form onSubmit={handleSubmit(onSubmit)}>
            <Input name="title" placeholder="Coachella Party" title="Event title" register={register} errors={errors} />
            <Input name="location" placeholder="Slottsplassen 1, 0010 Oslo" title="Event location" register={register} errors={errors} />
            <Input name="picture" placeholder="https://coolimage.png" title="Event picture" register={register} errors={errors} />
            <Input name="description" placeholder="This party is gonna be lit..." title="Event description" register={register} errors={errors} multiline/>
            <Input name="start_date_time" placeholder="2022-03-13T12:00" title="Event datetime" register={register} errors={errors}/>
          <Button mt={4} colorScheme='teal' isLoading={isSubmitting} type='submit'>
            Submit
          </Button>
        </form>
      </Container>
    </div>
  );
};

export default Event;
