import Head from 'next/head';
import { useUser } from 'contexts/User';
import { Heading, Container, Grid, IconButton } from '@chakra-ui/react';
import Card from 'components/index/Card';
import { GetServerSideProps, InferGetServerSidePropsType } from 'next';
import { IEvent } from 'utils/types';
import { cookieHandler, fetchBuilder } from 'utils/utils';
import { AddIcon } from '@chakra-ui/icons';
import router from 'next/dist/client/router';

export const getServerSideProps: GetServerSideProps = async (context) => {
  try {
    const cookies = context.req.headers.cookie;
    const user_session_cookie = cookieHandler(cookies, 'user_session');
    const res = await fetchBuilder(`events`, user_session_cookie);
    const events: IEvent[] = await res.data;
    return {
      props: { events },
    };
  } catch (error) {
    return {
      redirect: {
        destination: '/login',
        permanent: false,
      },
    };
  }
};

const Dashboard = ({ events }: InferGetServerSidePropsType<typeof getServerSideProps>) => {
  const user = useUser();
  return (
    <>
      <Head>
        <title>Xenia</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Container maxW='container.lg'>
        <Heading size='2xl' m='25px 0'>
          My Events <IconButton variant='outline' isRound colorScheme='teal' aria-label='Add event' onClick={() => router.push('/event')} icon={<AddIcon />} />
        </Heading>
        <Container centerContent maxW='container.xl'>
          <Grid templateColumns='repeat(3, 1fr)' gap={6}>
            {events?.map((event: IEvent) => (
              <Card key={event.id} event={event} />
            ))}
          </Grid>
        </Container>
      </Container>
    </>
  );
};

export default Dashboard;
